In [20]:
import numpy as np

# 5 random Gaussian varialbes stored in array
a = np.random.randn(5)

In [21]:
print(a)

[ 0.52363808  1.03122875 -0.0944527  -2.34943346 -0.00301575]


In [22]:
# it is neither a row vector or a column vector
print(a.shape)

(5,)


In [23]:
# here is the issue of transpose of a
# it will be as same as original a
print(a.T)

[ 0.52363808  1.03122875 -0.0944527  -2.34943346 -0.00301575]


In [24]:
# inner product gives as real number 
# because it is not a real product of a and transpose of a)
print(np.dot(a, a.T))

6.86639757475


In [26]:
# WE SHOULD NOT USE ANY OBJECT THAT HAS (n,)
# THIS IS CALLED "Rank 1 Array", neither a row or a column vector
# INSTEAD WE SHOULD USE THE FOLLOWING ONES.
 a = np.random.randn(5,1)
# OR optional, we can call RESHAPE function like that
# a = a.reshape(5,1)

print(a)

[[ 0.52363808]
 [ 1.03122875]
 [-0.0944527 ]
 [-2.34943346]
 [-0.00301575]]


In [10]:
#it is now column vector. 
print(a.shape)

(5, 1)


In [15]:
# transpose of A is a row vector
print(a.T)

[[ 0.88547478 -0.58176226  0.61387296  1.06938143  0.05659591]]


In [16]:
# shape of transpose of A
print(a.T.shape)

(1, 5)


In [17]:
# product of this a vector and transpose of a vector will give us a 
# outer product result which is going to be a (5,5) matrix
calc = np.dot(a, a.T)
print(calc)

[[ 0.78406558 -0.51513581  0.54356903  0.94691029  0.05011425]
 [-0.51513581  0.33844733 -0.35712813 -0.62212576 -0.03292536]
 [ 0.54356903 -0.35712813  0.37684002  0.65646435  0.0347427 ]
 [ 0.94691029 -0.62212576  0.65646435  1.14357665  0.06052261]
 [ 0.05011425 -0.03292536  0.0347427   0.06052261  0.0032031 ]]


In [18]:
# it is a 5,5 matrix
print(calc.shape)

(5, 5)
