In [4]:
import numpy as np
a = np.random.randn(2,3)
print('A')
print(a)
print('*' * 10)

b = np.random.randn(2,1)
print('B')
print(b)
print('*' * 10)
c = a + b
print('C')
print(c)
print('*' * 10)

print('Shape of C')
print(c.shape)

A
[[ 1.30088556 -0.43082145  1.07012553]
 [ 0.96288589 -0.60946549 -0.57060877]]
**********
B
[[ 1.18632775]
 [-1.86392964]]
**********
C
[[ 2.48721331  0.7555063   2.25645329]
 [-0.90104375 -2.47339513 -2.43453841]]
**********
Shape of C
(2, 3)


In [5]:
a = np.random.randn(4,3)
print('A')
print(a)
print('*' * 10)
b = np.random.randn(3,2)
print('B')
print(b)
print('*' * 10)
c = a * b
print('C')
print(c)
print('*' * 10)
print('Shape of C')
print(c.shape)

A
[[ 0.22664478  0.60493256  0.00992736]
 [ 2.20853672 -0.55545093  0.72704096]
 [ 1.35776243 -0.56942359  1.64928206]
 [-0.82705701 -1.91250082  1.17317006]]
**********
B
[[-0.18771819  0.26108063]
 [ 0.50224163  1.35389117]
 [-0.3054836   0.78638834]]
**********


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [7]:
a = np.random.randn(10000,50)
print('A')
print(a)
print('*' * 10)
b = np.random.randn(300, 15)
print('B')
print(b)
print('*' * 10)
c = np.dot(a,b)
print('C')
print(c)
print('*' * 10)
print('Shape of C')
print(c.shape)

A
[[ 1.86913598  0.48841143  0.92722818 ..., -0.01357168 -1.78886757
   0.22371165]
 [-0.51791176  0.24148572  0.00628409 ...,  1.32001014  0.15166995
   0.54006193]
 [-0.12810871  1.25621181 -0.66179253 ...,  1.02461936  0.39990895
   1.33987594]
 ..., 
 [ 0.92455562  0.16989809 -0.71067646 ...,  0.05091817 -2.03656804
  -0.14018263]
 [ 1.10183728  0.13779058  0.93724495 ...,  1.05206772 -0.88766629
  -0.482449  ]
 [-0.78052733  1.7151497  -1.72678432 ..., -0.47370495  1.0714866
  -1.14050637]]
**********
B
[[-2.32747129  0.58687888  0.55232747 ..., -0.75190208 -0.54357527
  -1.21424611]
 [-0.50037571  0.30056351 -0.12161582 ...,  0.68795521 -1.74973712
  -0.91356162]
 [ 0.18329133 -0.23392555 -0.15855448 ..., -0.220245   -0.56529994
   0.83426451]
 ..., 
 [ 0.5846762  -2.10528289  0.75828974 ...,  0.07209809 -0.5379038
  -0.92911517]
 [ 0.07726298  1.26082779 -0.7702171  ..., -0.08453616  1.04161631
   1.83406555]
 [-0.22799668 -0.11679362 -0.36599305 ...,  1.57396273 -0.53764159
   

ValueError: shapes (10000,50) and (300,15) not aligned: 50 (dim 1) != 300 (dim 0)

In [18]:
a = np.random.randn(3,3)
print('A')
print(a)
print('*' * 10)
b = np.random.randn(3, 1)
print('B')
print(b)
print('*' * 10)
    
c = a * b
print('C')
print(c)
print('*' * 10)
print('Shape of C')
print(c.shape)

A
[[-0.9492829  -2.56425912 -0.36904964]
 [-0.38402994  0.30711671  1.31600301]
 [ 0.45725336 -0.09717005 -0.59875639]]
**********
B
[[-0.36819899]
 [ 0.62836748]
 [ 0.38290264]]
**********
C
[[ 0.34952501  0.94415763  0.13588371]
 [-0.24131193  0.19298215  0.8269335 ]
 [ 0.17508352 -0.03720667 -0.2292654 ]]
**********
Shape of C
(3, 3)


In [25]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]],
                 [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [26]:
image.shape

(4, 3, 2)